artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: https://github.com/abhay560/Text-Summarizer-Project/raw/refs/heads/main/summarizer-data.zip
    local_data_files: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion